account controller and view review factory and seeder
j238267431/Renovation_Marketplace pull request #29
Opened 2021-04-10 19:26 UTC by j238267431

2021-04-11 00:16 UTC, izoya commented on routes/web.php
> +Route::middleware('auth')->group(function(){
можно добавить ->prefix('account') и далее не писать везде "account"

2021-04-11 00:28 UTC, izoya requested changes

2021-04-11 00:28 UTC, izoya commented on routes/web.php
> +  Route::get('account/customer', function (){
Странно, когда нет выхода на страницу /account (404), а вместо неё /account/customer. Зачем нам вообще этот customer нужен? Я уже задавала этот вопрос и вроде же решили через роли реализовать этот функционал?
Точно должна быть страница /account

2021-04-11 00:28 UTC, izoya commented on routes/web.php
> +  )->name('account.tasks');
Здесь нужен отдельный контроллер на каждый случай
Controllers\Account\TasksController
Controllers\Account\OrdersController

2021-04-11 00:30 UTC, izoya commented on resources/views/account/orders.blade.php
> +
@include('components.account.navigation') – компоненты подключаются как <x-account-navigation>

2021-04-11 00:43 UTC, izoya requested changes

2021-04-11 00:43 UTC, izoya commented on resources/views/account/orders.blade.php
> +
Это правое меню нужно вынести в отдельный компонент, оно же повторяется на всех страницах аккаунта

2021-04-11 00:43 UTC, izoya commented on app/Http/Controllers/Account/AccountController.php
> +      $tasks = Task::all()->where('user_id', '=', Auth::id());
$tasks= Auth::user()->tasks;
    $orders = Auth::user()->orders;

2021-04-11 14:32 UTC, j238267431 commented on routes/web.php
> +  Route::get('account/customer', function (){
не понял про 404? Нужно ее куда то добавить?

2021-04-11 14:33 UTC, j238267431 commented on routes/web.php
> +  )->name('account.tasks');
ok

2021-04-11 14:34 UTC, j238267431 commented on resources/views/account/orders.blade.php
> +
через <x- не получилось почему то из надо как то регистрировать? Потому что тупо для примера вставлял компоненты Алексея чтобы проверить работает или нет, так они вставлялись а мои нет

2021-04-11 14:36 UTC, j238267431 commented on resources/views/account/orders.blade.php
> +
имеешь ввиду блок со ссылками список заказов список исполнителей?

2021-04-11 14:38 UTC, j238267431 commented on app/Http/Controllers/Account/AccountController.php
> +      $tasks = Task::all()->where('user_id', '=', Auth::id());
ok

2021-04-11 16:01 UTC, j238267431 commented on resources/views/account/orders.blade.php
> +
как bootstrapом сделать чтобы ссылки менялись на неактивные

2021-04-11 22:14 UTC, izoya commented on resources/views/account/orders.blade.php
> +
> имеешь ввиду блок со ссылками список заказов список исполнителей?

Да

2021-04-11 22:17 UTC, izoya commented on resources/views/account/orders.blade.php
> +
> как bootstrapом сделать чтобы ссылки менялись на неактивные

Посмотри пример в файле /resources/views/includes/menu.blade.php

2021-04-11 22:27 UTC, izoya commented on routes/web.php
> +  Route::get('account/customer', function (){
Если перейти на страницу/account, будет 404

2021-04-11 22:29 UTC, rnikitav requested changes
404 ошибка выходит по роуту страницу /account а ты сделал роут Route::get('account/customer)  Зои не нравится такие роуты) она хочет лаконично все) поменяй просто роут удали customer)

2021-04-11 22:29 UTC, rnikitav commented on app/Http/Controllers/Account/AccountController.php
> +      $tasks = Task::all()->where('user_id', '=', Auth::id());
Зои вариант лучше.

2021-04-11 22:29 UTC, rnikitav commented on routes/web.php
> +  )->name('account.tasks');
Я не пойму. У нас будет 3 контроллера Task? один в корне? другой в Account? который будет разделяться на два? одни таски выводить для отдельного покупателя, который оставил таск, а другой для компаний, чтобы они видели все таски? А зачем тогда App\Http\Controllers\TaskController тогда? незареганный пользователь сможет сделать заказ?

2021-04-11 22:31 UTC, rnikitav commented on routes/web.php
> +  Route::get('account/customer', function (){
404 ошибка выходит по роуту страницу /account а ты сделал роут Route::get('account/customer) Зои не нравится такие роуты) она хочет лаконично все) поменяй просто роут удали customer)

2021-04-12 10:58 UTC, j238267431 commented on resources/views/account/orders.blade.php
> +
не получилось сделать а разбираться долго предлагаю оставить как есть или кто знает поправьте

2021-04-12 11:55 UTC, merged